listeners.tcp.default = 5672
management.tcp.port = 15672
heartbeat = 60
consumer_timeout = 1800000
vm_memory_high_watermark.absolute = 768MiB
disk_free_limit.absolute = 1GB
log.console = true
log.console.level = info
cluster_partition_handling = pause_minority
queue_leader_locator = balanced
