[agent]
  interval = "15s"
  flush_interval = "15s"
[[inputs.rabbitmq]]
  url = "http://rabbit1:15672"
  username = "monitoring"
  password = "monitoring-pass"
  metric_include = ["overview", "node", "queue", "exchange"]
[[outputs.prometheus_client]]
  listen = ":9273"
